# Generated by Django 2.2.16 on 2021-08-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210828_1732'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_following_user_following',
        ),
    ]
